"""Structure PF2e feat prerequisite strings for `build.list_available_feats`.

Feat prerequisites in the source data are free-text display strings (e.g.
"trained in Medicine", "Strength +2") with no adjacent machine-readable
field. The Phase 0 spike (scripts/spike_prerequisites.py) measured that
~84% of the ~4,500 prerequisite strings across all official feats are
confidently auto-parseable with the patterns below plus a verified
cross-reference against known feat/feature/heritage/background/ancestry
names; the rest is a genuine unparseable tail surfaced to callers as
"unresolved" rather than silently dropped or guessed at.

`prerequisite_overrides.json` is a hand-maintained, version-controlled file
(not regenerated by ingestion) for entries this parser can't structure --
keyed by the exact raw prerequisite text, so it keeps matching on every
re-ingestion as long as the upstream text doesn't change, and stops
matching (surfacing back as unresolved) if errata changes the wording.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

_SKILL_RANK = re.compile(
    r"^(trained|expert|master|legendary) in ([\w'()\- ]+?)$", re.IGNORECASE
)
_SKILL_RANK_LIST = re.compile(
    r"^(trained|expert|master|legendary) in ([\w'()\-, ]+?)$", re.IGNORECASE
)
_KNOWN_SKILLS = {
    "acrobatics", "arcana", "athletics", "crafting", "deception", "diplomacy",
    "intimidation", "medicine", "nature", "occultism", "performance", "religion",
    "society", "stealth", "survival", "thievery",
}
# Generic trailing category words PF2e prerequisite text appends to a
# specific name that itself doesn't include the word (e.g. 'dragonscaled
# kobold heritage' for the heritage named 'Dragonscaled Kobold'). Kept as
# an explicit curated set, not "strip any trailing word" -- unrestricted
# stripping produces real false positives, e.g. 'Efficient Alchemy' would
# wrongly resolve to an unrelated Kingmaker effect named 'Efficient', and
# 'Medium Size' to an unrelated class feature named 'Medium'.
_SUFFIX_STRIP_WORDS = {"heritage", "muse"}
_ABILITY_SCORE = re.compile(
    r"^(strength|dexterity|constitution|intelligence|wisdom|charisma) "
    r"(\+\d+|\d+ or higher)$",
    re.IGNORECASE,
)
_CHARACTER_LEVEL = re.compile(r"^(character )?level (\d+)$", re.IGNORECASE)
_COMPOUND_HINT = re.compile(r"\bor\b|\band\b|;", re.IGNORECASE)
_LIST_SPLIT = re.compile(r",\s*(?:or\s+)?|\s+or\s+")

_OVERRIDES_PATH = Path(__file__).parent / "prerequisite_overrides.json"


class PrerequisiteParser:
    def __init__(self, name_index: set[str], overrides: dict[str, Any] | None = None):
        self.name_index = name_index
        self.overrides = overrides or {}

    @classmethod
    def load(cls, name_index: set[str]) -> "PrerequisiteParser":
        overrides = {}
        if _OVERRIDES_PATH.exists():
            raw = json.loads(_OVERRIDES_PATH.read_text())
            overrides = {k: v for k, v in raw.items() if not k.startswith("_")}
        return cls(name_index, overrides)

    def parse(self, raw_text: str) -> dict[str, Any]:
        """Returns {"kind": ..., "structured": <json-serializable | None>}."""
        text = raw_text.strip()

        if text in self.overrides:
            return {"kind": "override", "structured": self.overrides[text]}

        if m := _SKILL_RANK.match(text):
            rank, skill = m.groups()
            return {
                "kind": "skill_rank",
                "structured": {"skill": skill.strip().lower(), "rank": rank.lower()},
            }

        if result := self._try_skill_rank_list(text):
            rank, skills = result
            return {"kind": "skill_rank_any", "structured": {"skills": skills, "rank": rank}}

        if m := _ABILITY_SCORE.match(text):
            ability, threshold = m.groups()
            return {
                "kind": "ability_score",
                "structured": {"ability": ability.lower(), "threshold": threshold},
            }

        if m := _CHARACTER_LEVEL.match(text):
            return {"kind": "character_level", "structured": {"level": int(m.group(2))}}

        if text.lower() in self.name_index:
            return {"kind": "named_reference", "structured": {"name": text}}

        if name := self._try_suffix_stripped(text):
            return {"kind": "named_reference", "structured": {"name": name}}

        if names := self._try_compound_named(text):
            return {"kind": "compound_named", "structured": {"any_of": names}}

        if names := self._try_suffix_stripped_compound(text):
            return {"kind": "compound_named", "structured": {"any_of": names}}

        return {"kind": "unresolved", "structured": None}

    def _strip_suffix_word(self, text: str) -> str | None:
        """'dragonscaled kobold heritage' -> 'Dragonscaled Kobold' (real
        name in the heritages pack). Only strips a single trailing word
        from _SUFFIX_STRIP_WORDS, and only returns a match if the
        remaining prefix is itself a verbatim name_index hit."""
        words = text.split()
        if len(words) < 2:
            return None
        last = words[-1].lower().rstrip(".,")
        if last not in _SUFFIX_STRIP_WORDS:
            return None
        prefix = " ".join(words[:-1])
        return prefix if prefix.lower() in self.name_index else None

    def _try_suffix_stripped(self, text: str) -> str | None:
        return self._strip_suffix_word(text)

    def _try_suffix_stripped_compound(self, text: str) -> list[str] | None:
        """Composes suffix-stripping with OR-list splitting for texts like
        'Cactus Leshy or Pine Leshy heritage' (real names 'Cactus Leshy',
        'Pine Leshy' -- a suffix word shared once at the end of the whole
        list) and 'bakuwa lizardfolk heritage or makari lizardfolk
        heritage' (real names 'Bakuwa Lizardfolk', 'Makari Lizardfolk' --
        the suffix word repeated after every item). Each split part is
        checked as either a direct name_index hit (covers a mixed list
        like 'Fang Sharpener or razortooth goblin heritage', where one
        side is already a bare feat name) or a single-trailing-word strip.
        Deliberately strict -- every part must resolve one of those two
        ways, or the whole text stays unresolved rather than risk
        mis-structuring an AND/qualifier clause (e.g. 'swimming animal
        heritage, aquatic') as an OR-list. Doesn't attempt the harder case
        where the shared suffix is a multi-word phrase not itself a
        _SUFFIX_STRIP_WORDS entry (e.g. 'abyssal or carcharodon merfolk
        heritage', where 'abyssal' alone needs 'merfolk' inserted before
        'heritage', not just a trailing-word strip) -- left unresolved."""
        if not _COMPOUND_HINT.search(text):
            return None
        parts = [p.strip() for p in _LIST_SPLIT.split(text) if p.strip()]
        if len(parts) < 2:
            return None
        resolved = []
        for part in parts:
            if part.lower() in self.name_index:
                resolved.append(part)
            elif stripped := self._strip_suffix_word(part):
                resolved.append(stripped)
            else:
                return None
        return resolved

    def _try_skill_rank_list(self, text: str) -> tuple[str, list[str]] | None:
        """'trained in Arcana, Nature, Occultism, or Religion': satisfied
        by reaching the given rank in ANY one of the listed skills.
        Deliberately strict -- bails unless every split item is a real
        skill or an 'X Lore' name, so AND-lists ('Society, and Thievery'),
        non-skill categories ('light armor'), and trailing qualifier
        clauses ('depending on your chosen tradition') aren't silently
        mis-structured as an any-of check."""
        m = _SKILL_RANK_LIST.match(text)
        if not m:
            return None
        rank, skills_text = m.groups()
        if "," not in skills_text and not _COMPOUND_HINT.search(skills_text):
            return None  # single skill -- already handled by _SKILL_RANK
        parts = [p.strip() for p in _LIST_SPLIT.split(skills_text) if p.strip()]
        if len(parts) < 2 or not all(self._is_skill_like(p) for p in parts):
            return None
        return rank.lower(), parts

    @staticmethod
    def _is_skill_like(text: str) -> bool:
        t = text.strip().lower()
        return t in _KNOWN_SKILLS or (t.endswith(" lore") and len(t.split()) >= 2)

    def _try_compound_named(self, text: str) -> list[str] | None:
        """PF2e's shared-suffix list phrasing, e.g. 'Acrobat, Celebrity, Dandy,
        or Gladiator Dedication' == each of {Acrobat, Celebrity, Dandy,
        Gladiator} + ' Dedication'. Returns the resolved full names, or None."""
        if not _COMPOUND_HINT.search(text):
            return None
        parts = [p.strip() for p in _LIST_SPLIT.split(text) if p.strip()]
        if len(parts) < 2:
            return None

        last_words = parts[-1].split()
        for cut in range(len(last_words) - 1, 0, -1):
            suffix = " ".join(last_words[cut:])
            candidates = [p if i == len(parts) - 1 else f"{p} {suffix}" for i, p in enumerate(parts)]
            if all(c.lower() in self.name_index for c in candidates):
                return candidates

        if all(p.lower() in self.name_index for p in parts):
            return parts

        return None


def build_name_index(packs: dict[str, list[dict]]) -> set[str]:
    """Every name that could plausibly be referenced in a prerequisite string."""
    relevant_packs = [
        "feats", "class-features", "ancestry-features", "heritages",
        "kingmaker-features", "backgrounds", "ancestries", "actions",
        "spells", "pathfinder-society-boons",
    ]
    names = set()
    for pack_name in relevant_packs:
        for item in packs.get(pack_name, []):
            names.add(item["name"].strip().lower())
    return names
